a : (array_like)
输入数组
shift : (int or tuple of ints)
滚动的长度。如果是提供元组的话，下面的轴参数的维度也应该跟shift维度一样。
axis : (int or tuple of ints, optional)
滚动的维度，0为垂直滚动，1为水平滚动（默认情况下，即参数为None时，数组在移位之前会被变成扁平化，之后会恢复原始形状。）

In [1]:
import numpy as np
import pandas as pd

# 原始 action 序列
actions = np.array([
    26, 20, 22, 22, 22, 19, 19, 19, 19, 19, 19, 19, 19, 15, 15, 15, 6, 6, 8, 8, 20, 20, 20, 20, 20, 20, 20, 20,
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 15, 15, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 10, 10,
    20, 20, 20, 10, 10, 20, 20, 20, 10, 10, 20, 20, 20, 10, 10, 20, 20, 20, 20, 10, 10, 20, 20, 20, 20, 20, 10, 8
])

# 定义错位窗口移动函数
def shift_actions(actions, shift_step):
    return np.roll(actions, shift_step)

# 制作多个错位窗口的数据
shift_steps = [1, 5, 10, 15]  # 可以根据需求调整错位步长
shifted_data = {f'shift_{step}': shift_actions(actions, step) for step in shift_steps}

# 转换为 DataFrame 方便查看
df_shifted = pd.DataFrame(shifted_data)
# 增加了一行原始的数据部分
df_shifted['original'] = actions

In [4]:
# df_shifted['original']
df_shifted.head()

   shift_1  shift_5  shift_10  shift_15  original
0        8       20        20        10        26
1       26       20        10        10        20
2       20       20        10        20        22
3       22       10        20        20        22
4       22        8        20        20        22

In [ ]:
action_array = np.array([26, 20, 22, 22, 22, 19, 19, 19, 19, 19, 19, 19, 19, 15, 15, 15, 6, 6, 8, 8,
                         20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 15,
                         15, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 10, 10, 20, 20, 20,
                         10, 10, 20, 20, 20, 10, 10, 20, 20, 20, 10, 10, 20, 20, 20, 20, 10, 10, 20,
                         20, 20, 20, 20, 10, 8])

# 向前移动 30 步
shift_forward = np.roll(action_array, -30)
shift_forward[-30:] = action_array[-1]

# 向后移动 30 步
shift_backward = np.roll(action_array, 30)
shift_backward[:30] = action_array[0]

# 生成 DataFrame
df_shift_30 = pd.DataFrame({
    'Original_Action': action_array,
    'Shift_Forward_30': shift_forward,
    'Shift_Backward_30': shift_backward
})

In [3]:
df_shift_30.head()

   Original_Action  Shift_Forward_30  Shift_Backward_30
0               26                20                 26
1               20                20                 26
2               22                20                 26
3               22                20                 26
4               22                20                 26